#!/bin/bash
sudo su
dnf install git -y
git clone https://github.com/Caiwen612/Aws-Cloud.git
cd Aws-Cloud
git fetch
git pull
dnf install python-pip -y
pip3 install flask pymysql boto3 reportlab
python3 EmpApp.py